name: Release

on:
  push:
    tags:
      - 'cli-*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          supabase/pgadmin-schema-diff
        flavor: |
          latest=false
        tags: |
          type=ref,event=tag
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v3
      with:
        push: true
        file: Dockerfile.cli
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  publish:
    needs:
      - release
    # Call workflow explicitly because events from actions cannot trigger more actions
    uses: ./.github/workflows/mirror.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit
