name: Release

on:
  push:
    tags:
      - 'cli-*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set env
      run: |
        echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build container
      run: |
        docker build -t pgadmin-schema-diff -f Dockerfile.cli .
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to dockerhub
      run: |
        docker tag pgadmin-schema-diff supabase/pgadmin-schema-diff:latest
        docker push supabase/pgadmin-schema-diff:latest

        docker tag pgadmin-schema-diff supabase/pgadmin-schema-diff:$TAG
        docker push supabase/pgadmin-schema-diff:$TAG